[package]
name = "dots"
version = "0.2.1"
description = "A cli for managing all your dot(file)s"
license = "MIT"
authors = ["Michael Mullins <michael@webdesserts.com>"]

[dependencies]
# terminal
clap = "^2.20"

# logging
env_logger = "^0.4.0"
log = "^0.3.6"
colored = "^1.4.0"

# serialization
serde = "^0.9.6"
serde_derive = "^0.9.6"
toml = "^0.3.0"
