[package]
name = "dots"
version = "0.2.1"
description = "A cli for managing all your dot(file)s"
license = "MIT"
authors = ["Michael Mullins <michael@webdesserts.com>"]

[dependencies]
camino = { version = "1.0.1", features = ['serde1']}

# terminal
clap = "2.33.3"
dirs = "3.0.1"

# logging
env_logger = "0.8.3"
log = "0.4.11"
colored = "2.0.0"

# serialization
serde = "1.0.115"
serde_derive = "1.0.115"
toml = "0.5.6"
