[package]
name = "test_utils"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.0.5"
similar = { version = "2.1.0", features = ["inline"] }
tempfile = "3.2.0"
walkdir = "2.3.2"
utils = { package = "dots_internal_utils", version = "^0.4.0", path = "../utils" }
anyhow = "1.0.53"

[features]
