[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.0.5"
console = "0.15.0"
dirs = "4.0.0"
failure = "0.1.8"
walkdir = "2.3.2"
