[package]
name = "dots_internal_utils"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "A set of utility modules intended to be used internally by the dots crate"
authors = ["Michael Mullins <michael@webdesserts.com>"]
repository = "https://github.com/webdesserts/dots-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
camino = "1.0.5"
dirs = "4.0.0"
walkdir = "2.3.2"
owo-colors = "^3"
